//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.10.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace CompanyCrudTwo.HelperClasses
{
	/// <summary>Field Creation Class for entity DepartmentEntity</summary>
	public partial class DepartmentFields
	{
		/// <summary>Creates a new DepartmentEntity.DepartmentId field instance</summary>
		public static EntityField2 DepartmentId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(DepartmentFieldIndex.DepartmentId); }}
		/// <summary>Creates a new DepartmentEntity.Name field instance</summary>
		public static EntityField2 Name { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(DepartmentFieldIndex.Name); }}
	}

	/// <summary>Field Creation Class for entity EmployeeEntity</summary>
	public partial class EmployeeFields
	{
		/// <summary>Creates a new EmployeeEntity.DepartmentId field instance</summary>
		public static EntityField2 DepartmentId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(EmployeeFieldIndex.DepartmentId); }}
		/// <summary>Creates a new EmployeeEntity.EmployeeId field instance</summary>
		public static EntityField2 EmployeeId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(EmployeeFieldIndex.EmployeeId); }}
		/// <summary>Creates a new EmployeeEntity.Name field instance</summary>
		public static EntityField2 Name { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(EmployeeFieldIndex.Name); }}
		/// <summary>Creates a new EmployeeEntity.Salary field instance</summary>
		public static EntityField2 Salary { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(EmployeeFieldIndex.Salary); }}
	}
	

}